// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkdwfC0mFfIuSV6D_AuxeqlUjpccr-dMs',
    appId: '1:893437431950:web:f5c7502dc8819f57c779df',
    messagingSenderId: '893437431950',
    projectId: 'onlineelectronicstoreproject',
    authDomain: 'onlineelectronicstoreproject.firebaseapp.com',
    storageBucket: 'onlineelectronicstoreproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrLn3drqC6z9OiBSLjFPxgXoiryRodoEY',
    appId: '1:893437431950:android:11d277fcff05b231c779df',
    messagingSenderId: '893437431950',
    projectId: 'onlineelectronicstoreproject',
    storageBucket: 'onlineelectronicstoreproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0S_RS8zHuZs5wDcBu036Pj56iIGjc2Z0',
    appId: '1:893437431950:ios:923b769ae2d745f1c779df',
    messagingSenderId: '893437431950',
    projectId: 'onlineelectronicstoreproject',
    storageBucket: 'onlineelectronicstoreproject.appspot.com',
    iosBundleId: 'com.example.onlineElectronicShoppingApp',
  );
}
